#ifndef ASCII_ENUMS_H
#define ASCII_ENUMS_H

typedef enum{
	ASCII_GRID_OUT_OF_MEMORY,
	ASCII_GRID_SUCCESS,
	ASCII_GRID_BAD_ARGUMENT,
	ASCII_GRID_NOT_OPEN,
	ASCII_GRID_OUT_OF_BOUNDS,
	ASCII_GRID_TOO_SMALL,
	ASCII_GRID_BAD_MAX_FRAME,
	ASCII_GRID_COULDNT_SAVE_IMAGE,
	ASCII_GRID_CANT_GENERATE,
	ASCII_GRID_ERROR
} ASCIIGridStatus;

typedef enum{
	ASCII_FONT_TINY = 0,
	ASCII_FONT_MEDIUM_BOLD,
	ASCII_FONT_GIANT,
	ASCII_FONT_SMALL,
	ASCII_FONT_TERM
} ASCIIFont;

#endif
